### PR TITLE
KiLib v2.5.0

### PR DESCRIPTION
**Pull request by deniscohen**
I think we should up the number so v2.5.0. Everyone ok with this?
@haydn-jones @oparkins What about the CHANGELOG md file?

### CODE REVIEW

**Comment by oparkins** [comment]
Yea, I think v2.5.0 is good. With the major CMake change, though it doesn't break previous software, the minor version increase is a good call.

I was going to copy this format: https://github.com/olivierlacan/keep-a-changelog/edit/master/CHANGELOG.md. I just pushed it.. See if that is what you were thinking.

**Comment by deniscohen** [comment]
> Yea, I think v2.5.0 is good. With the major CMake change, though it doesn't break previous software, the minor version increase is a good call.
> 
> I was going to copy this format: https://github.com/olivierlacan/keep-a-changelog/edit/master/CHANGELOG.md. I just pushed it.. See if that is what you were thinking.

@oparkins Can you make this small modifications to the CHANGELOG:
- Add date after version (2020-03-03)
- Add `Add truncated normal distribution` (to the Added section)
- change: `Change MDSTAB Safety Factor to include passive force`

@oparkins Can you remove the comment I left in MDSTAB.cpp: line 78? Thanks

Else LGTM.

**Comment by deniscohen** [comment]
@oparkins Would it be possible to add in the README the syntax for building using Ninja for the debug/test? Thanks

**Comment by oparkins** [comment]
Okay. Just pushed changes. How does that look?

**Comment by deniscohen** [comment]
> Okay. Just pushed changes. How does that look?

LGTM. Ready for new version!

**Review by oparkins — APPROVED** [review]

**Pull request merged**
