### PR TITLE
Issue8: Reading data from TIF files into rasters

### PR DESCRIPTION
**Pull request by ohunter**
A working implementation of converting tif files to `KiLib::Raster` objects. It uses `libtiff` (version 4.2.0) to read and process all the data. It has been tested with all the tif files I had available the MSE between what was produced by `gdal_translate` and this was `5.706029586683597e-18` with [DEM.tif](https://github.com/CoSci-LLC/PRIMULATests/blob/main/Data/Study_Test_UNIPV/DEM.tif) (all the others had an MSE of `0.0`). There are a few things I have declared as not supported as of right now and that is:

- Multi-raster images.
- Tiled images (simply because I dont know if tiled images can be read using scanline).

A few assumptions I have made:

- The image needs to define its storage format.
- If no scaling is available it is 1:1
- If no latitude or longitude is specified it is 0, 0
- If no `nodatavalue` present it is `-9999`

I have also not invested a lot of time into stopping `libtiff` from building all of the tools that it normally builds which is something to address in the future. Maybe through our own cmake file or by setting the appropriate options before building it. Not sure how to integrate that into how cmake handles it.

### CODE REVIEW

**Review by haydn-jones — COMMENTED** [review]
This doesn't build on windows which is a problem. What do you think about inferring the filetype from the ending? We have a single constructor, if the filename ends in something like "dem" or "asc" we load it in how we usually do and if it ends in "tif" or "tiff" we load it in with the tiff method.

Have you tried loading a tiff in with this class and writing it out with our method and then comparing it to the output of a tool that converts tiff's to the raster format we output in?

@deniscohen Do we need a method to write the file out as a tif format? If so, we could use the same method as described above with the constructor where based on the file ending we write it out as a different format.

**Comment by deniscohen** [comment]
Yes we should output in tif format if input is in tif format. If input is asc then write output in asc

**Comment by ohunter** [comment]
> This doesn't build on windows which is a problem. What do you think about inferring the filetype from the ending? We have a single constructor, if the filename ends in something like "dem" or "asc" we load it in how we usually do and if it ends in "tif" or "tiff" we load it in with the tiff method.

Sure, although for code organizations sake I think the constructor should call one of two private constructors which handle their respective filetypes.

> Have you tried loading a tiff in with this class and writing it out with our method and then comparing it to the output of a tool that converts tiff's to the raster format we output in?

Yes, that is how I got the MSE for the different rasters. 

> @deniscohen Do we need a method to write the file out as a tif format? If so, we could use the same method as described above with the constructor where based on the file ending we write it out as a different format.

Good idea, I might need a little more time to get that done.

**Comment by haydn-jones** [comment]
- [ ] Investigate windows compilation
- [ ] Output in tif format if read in in tif format
- [ ] Single constructor that determines load method based on file ending
- [ ] Run in valgrind to please Haydn

**Comment by ohunter** [comment]
>     * [ ]  Run in valgrind to please Haydn
Compiled with debug:
image

Compiled with Release:
image

**Comment by haydn-jones** [comment]
LGTM. Can you test this with PRIMULA and valgrind to make sure there are no memory issues? Also, have you looked at making sure you can read in a tiff, write it out, read it in and its still the same? Or maybe even in tiff -> out to dem -> in as dem and making sure the data is the same. Don't want to foist a lot more work onto you though.

**Review by oparkins — COMMENTED** [review]
That poor `raster.cpp` has exploded in size, but I don't see a good way to split it all up. Everything seems to be in its proper place. 

I'll leave the true review to @haydn-jones  or @deniscohen  since I don't mess with the TIF Files. But style and format looks good.

**Comment by haydn-jones** [comment]
> That poor `raster.cpp` has exploded in size, but I don't see a good way to split it all up. Everything seems to be in its proper place.
> 
> I'll leave the true review to @haydn-jones or @deniscohen since I don't mess with the TIF Files. But style and format looks good.

I imagine we could have the raster header, the raster.cpp with *input format independent stuff*, and two extra files `readDEM.cpp` and `readTIFF.cpp` that implement methods that return a raster. The raster constructor would call the correct one.

**Comment by oparkins** [comment]
Yea, or since they perform both writes and reads, we can change the names to `raster_DEM.cpp` and `raster_TIFF.cpp`. 

Are there other formats that we might want to support in the future? If not, I think we can just leave it since they likely won't be looked at again. Otherwise, splitting them up now might set up a good practice for future supported formats.

**Review by deniscohen — DISMISSED** [review]

**Comment by ohunter** [comment]
> That poor `raster.cpp` has exploded in size, but I don't see a good way to split it all up. 

I felt the exact same way. Maybe @haydn-jones is on to something with the separation idea. Even though these are the only two formats we may support I think that is probably the best way of going at it.

> Also, have you looked at making sure you can read in a tiff, write it out, read it in and its still the same? Or maybe even in tiff -> out to dem -> in as dem and making sure the data is the same.

I can definitely do that, although it will have to wait a few days. I will essentially just bake that directly in to the test I will write.

> Can you test this with PRIMULA and valgrind to make sure there are no memory issues?

I'll do that in a few days as well, although there shouldn't be that many changes from the report above where there were no reported issues.

**Comment by oparkins** [comment]
> > Also, have you looked at making sure you can read in a tiff, write it out, read it in and its still the same? Or maybe even in tiff -> out to dem -> in as dem and making sure the data is the same.
> 
> I can definitely do that, although it will have to wait a few days. I will essentially just bake that directly in to the test I will write.

Just as a friendly pointer for later, look at 

https://github.com/CoSci-LLC/KiLib-OSS/blob/fca02a6f2f047974e3a88976f0c74aa232c5abd3/KiLib/Utils/CSVReader.test.cpp#L75-L77 

for an example of how to use the test directory to read in files and such. I think you already knew that, but :man_shrugging:

**Comment by ohunter** [comment]
Valgrind output for @haydn-jones's sanity

image

**Comment by haydn-jones** [comment]
@ohunter So PRIMULA works with loading in TIFF datasets? Have you converted the malonno dataset to tiff and made sure the results were the same (or similar enough)?

**Comment by ohunter** [comment]
> @ohunter So PRIMULA works with loading in TIFF datasets? Have you converted the malonno dataset to tiff and made sure the results were the same (or similar enough)?

I'll do that tomorrow and upload the results

**Comment by ohunter** [comment]
@haydn-jones Given the following config I ended up with this
```
# Path to slope Raster | Type: TEXT:FILE
slopePath="../utils/slope_MALONNO.tif"

# Path to TWI Raster | Type: TEXT:FILE
twiPath="../utils/twi_MALONNO.tif"

# Path to soil type Raster | Type: TEXT:FILE
soilTypePath="../utils/soils_MALONNO_v2.tif"

# Path to soil depth Raster | Type: TEXT:FILE
soilDepthPath="../utils/soils_MALONNO.tif"

# Path to dusaf Raster | Type: TEXT:FILE
dusafPath="../utils/dusaf_MALONNO.tif"

# Path to probslope Raster | Type: TEXT:FILE
probslopePath="../utils/PROBSLOPE_MALONNO.tif"

# File extension for output rasters | Type: TEXT
outputExtension = ".asc"

# Seed for RNG | Type: UINT
seed = 69420

# The number of landslides to simulate | Type: UINT
numLandslides = 100

# Path to output directory | Type: TEXT
outputPath = "./tiff_test"
```
image

**Review by haydn-jones — APPROVED** [review]
LGTM, great work. I'll approve this as of now. @deniscohen tif files output in binary rather than ASCII so it looks like in most cases you get a great reduction in file size (one of our files went from 55M to 8M) and have no precision issues, we should consider making this our default output type if this is a commonly used format in the community.

**Comment by deniscohen** [comment]
@haydn-jones I'll have to ask what the client wants about output file format output. But we can make it the default. 
@ohunter Let's merge this into main if this is ready (looks like it). 
@oparkins Let's make a new version of KiLib-OSS (dev branch as suggested by @haydn-jones?) with all these changes and incorporate the changes also into KiLib.

**Pull request merged**
