### PR TITLE
KiLib v2.3.3 - More CMake Improvements and other goodies

### PR DESCRIPTION
**Pull request by oparkins**
Refactored CMake to be more developer friendly and manageable. Now there are CMakeLists.txt files for each directory and they are all included via add_subdirectory. I had to bump the support CMake version to be able to do this in a nicer fashion. Most systems will be fine though.  

Ubuntu 18.04 LTS does not have the support version. Though this can be solved by using Docker for the builds or compiling CMake from source. 

The README.md as also been updated with more instructions about how to use the included `stats` lib during builds.

### CODE REVIEW

**Comment by haydn-jones** [comment]
LGTM

**Review by haydn-jones — DISMISSED** [review]
LGTM

**Comment by haydn-jones** [comment]
Before this is merged I am wondering if we should update the README instructions for using KiLib to have KiLib be cached just like the other libs are.

**Review by haydn-jones — APPROVED** [review]
LGTM

**Review by deniscohen — APPROVED** [review]

**Pull request merged**
