### PR TITLE
MDSTAB - modification

### PR DESCRIPTION
**Pull request by alessiocislaghi**
I modified the file MDSTAB.cpp.
I removed "//" before Frd=... to include into the calculations also the passive force.
I inserted "//" before Frd=0

### CODE REVIEW

**Comment by haydn-jones** [comment]
Should we just add boolean arg `bool calcFrd` to the function call?

**Comment by deniscohen** [comment]
> Should we just add boolean arg `bool calcFrd` to the function call?

@haydn-jones Yes I think we should add that option with the default=TRUE (that would be in PRIMULA)
@haydn-jones This should eventually be merged into `dev` not `main`. When I try to change the destination branch I get some warnings. Can you see if these warnings are relevant? Thanks

**Comment by haydn-jones** [comment]
> > Should we just add boolean arg `bool calcFrd` to the function call?
> 
> @haydn-jones Yes I think we should add that option with the default=TRUE (that would be in PRIMULA)
> @haydn-jones This should eventually be merged into `dev` (or branch 39?) not `main`. When I try to change the destination branch I get some warnings. Can you see if these warnings are relevant? Thanks

I cant actually change the merge target, my permissions seem to be somewhat limited on this repo. @alessiocislaghi for future reference, we generally branch off `dev` and merge our stuff into dev, and then periodically merge `dev` into master.

**Comment by alessiocislaghi** [comment]
> > > Should we just add boolean arg `bool calcFrd` to the function call?
> > 
> > 
> > @haydn-jones Yes I think we should add that option with the default=TRUE (that would be in PRIMULA)
> > @haydn-jones This should eventually be merged into `dev` (or branch 39?) not `main`. When I try to change the destination branch I get some warnings. Can you see if these warnings are relevant? Thanks
> 
> I cant actually change the merge target, my permissions seem to be somewhat limited on this repo. @alessiocislaghi for future reference, we generally branch off `dev` and merge our stuff into dev, and then periodically merge `dev` into master.

Sorry. It was the first time I used git and github. Thus, in the future, I will push the modified branch and I will merge into "dev". That's clear now. Sorry again.

**Comment by haydn-jones** [comment]
> > > > Should we just add boolean arg `bool calcFrd` to the function call?
> > > 
> > > 
> > > @haydn-jones Yes I think we should add that option with the default=TRUE (that would be in PRIMULA)
> > > @haydn-jones This should eventually be merged into `dev` (or branch 39?) not `main`. When I try to change the destination branch I get some warnings. Can you see if these warnings are relevant? Thanks
> > 
> > 
> > I cant actually change the merge target, my permissions seem to be somewhat limited on this repo. @alessiocislaghi for future reference, we generally branch off `dev` and merge our stuff into dev, and then periodically merge `dev` into master.
> 
> Sorry. It was the first time I used git and github. Thus, in the future, I will push the modified branch and I will merge into "dev". That's clear now. Sorry again.

Not a problem, no need to apologize. @oparkins can we rebase this off of dev or something after the CMake stuff gets merged?

**Pull request merged**
