### PR TITLE
Issue17 | PRIMULA Improvements and general cleanup

### PR DESCRIPTION
**Pull request by haydn-jones**
- Using StatsLib for the current random functions we have where appropriate
- Added quantile calculation for the triangular distribution
- Added Stability and Factor of Safety modules
- Ran formatter on *all* files because some were improperly formatted

### CODE REVIEW

**Review by oparkins — COMMENTED** [review]
LGTM. I need to update the README and other version before final approval. I'm thinking of making this v2.4.0 since we are adding new functionality but nothing else has changed. What do you guys think?

**Comment by haydn-jones** [comment]
SoilDepth module now in. Pinging @deniscohen and @oparkins

**Review by ohunter — APPROVED** [review]
I can only approve to the extent of my involvement in some of the code, and those sections look good.

**Comment by haydn-jones** [comment]
> LGTM. I need to update the README and other version before final approval. I'm thinking of making this v2.4.0 since we are adding new functionality but nothing else has changed. What do you guys think?

Fine with me.

**Comment by oparkins** [comment]
Sounds good. I'll do that later tonight. Depending on Issue 9 on KiLib as well... I may wrap them up together

**Comment by oparkins** [comment]
@haydn-jones  If you could add another review, that would be fantastic :-)

**Comment by haydn-jones** [comment]
LGTM, though because I opened it I cant approve this pull request.

**Comment by haydn-jones** [comment]
Ah wait merge from KiLib (4ff58e3) deleted the qtri function. Let me add it back.

**Comment by haydn-jones** [comment]
LGTM now.

**Comment by haydn-jones** [comment]
Theres one more thing I want to throw in for the Raster class.

**Comment by haydn-jones** [comment]
Sorry I keep adding stuff and burning the CI time. Done now.

**Review by oparkins — APPROVED** [review]
Looks like everything is added

**Pull request merged**
