### PR TITLE
CMake Improvements and Raster Additions

### PR DESCRIPTION
**Pull request by oparkins**
- Fixed stat install and added Raster method
- Allows for use with FetchContent to have cleaner builds
- Updated README

### CODE REVIEW

**Comment by haydn-jones** [comment]
image
Getting this issue. Looks like it's trying to install to the default places and I cant tell how to set options for FetchContent

**Comment by haydn-jones** [comment]
Actually, the above is not a problem because the install step when using fetchcontent is disabled.

**Comment by oparkins** [comment]
So FetchContent doesn't perform the install step right away. It actually adds the cmake targets to the project and builds the fetched content with the current project. So it all happens at once and you don't have to supply any special variables like ExternalContent. This fixes a lot of build issues. For instance, if you specific `CC=gcc-9` to your cmake project, you would have to do that for the ExternalContent as well. With FetchContent, since it builds in the same context as your project, it just works.

To change the install location, use: `-DCMAKE_INSTALL_PREFIX=<install location>`

**Comment by haydn-jones** [comment]
With those recent commits PRIMULA builds.

**Review by haydn-jones — APPROVED** [review]

**Pull request merged**
