### PR TITLE
Add Hydrology module

### PR DESCRIPTION
**Pull request by deniscohen**
- Copy TopModel from SoilDepth into Hydrology module

### CODE REVIEW

**Comment by deniscohen** [comment]
@haydn-jones I have not yet removed the SoilDepth/TopModel. I'll let you do that as you change PRIMULA and also add the new functions for soil depth.

**Comment by haydn-jones** [comment]
@deniscohen can you check my work in `LinInterpDepth.cpp`?

**Review by deniscohen — COMMENTED** [review]
Can we change `computeDepth` to `ComputeDepth`? I prefer to have member functions start with a capital letter and leave the lower case for member data. Thanks

**Comment by deniscohen** [comment]
> @deniscohen can you check my work in `LinInterpDepth.cpp`?

Looks all good to me. Just requested a capital letter for `ComputeDepth`

**Pull request merged**
